
# This file is automatically generated, you probably don't want to edit this

jmvScaffoldOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvScaffoldOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            somevars = NULL,
            correlations = FALSE,
            regression = FALSE,
            focused = NULL,
            test = FALSE,
            msg1 = FALSE,
            msg2 = FALSE,
            msg3 = FALSE, ...) {

            super$initialize(
                package="jmvScaffold",
                name="jmvScaffold",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                default=NULL,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..somevars <- jmvcore::OptionVariables$new(
                "somevars",
                somevars,
                default=NULL,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "numeric"))
            private$..correlations <- jmvcore::OptionBool$new(
                "correlations",
                correlations,
                default=FALSE)
            private$..regression <- jmvcore::OptionBool$new(
                "regression",
                regression,
                default=FALSE)
            private$..focused <- jmvcore::OptionTerms$new(
                "focused",
                focused,
                default=NULL)
            private$..test <- jmvcore::OptionBool$new(
                "test",
                test,
                default=FALSE)
            private$..msg1 <- jmvcore::OptionBool$new(
                "msg1",
                msg1,
                default=FALSE)
            private$..msg2 <- jmvcore::OptionBool$new(
                "msg2",
                msg2,
                default=FALSE)
            private$..msg3 <- jmvcore::OptionBool$new(
                "msg3",
                msg3,
                default=FALSE)
            private$..residuals <- jmvcore::OptionOutput$new(
                "residuals")

            self$.addOption(private$..dep)
            self$.addOption(private$..somevars)
            self$.addOption(private$..correlations)
            self$.addOption(private$..regression)
            self$.addOption(private$..focused)
            self$.addOption(private$..test)
            self$.addOption(private$..msg1)
            self$.addOption(private$..msg2)
            self$.addOption(private$..msg3)
            self$.addOption(private$..residuals)
        }),
    active = list(
        dep = function() private$..dep$value,
        somevars = function() private$..somevars$value,
        correlations = function() private$..correlations$value,
        regression = function() private$..regression$value,
        focused = function() private$..focused$value,
        test = function() private$..test$value,
        msg1 = function() private$..msg1$value,
        msg2 = function() private$..msg2$value,
        msg3 = function() private$..msg3$value,
        residuals = function() private$..residuals$value),
    private = list(
        ..dep = NA,
        ..somevars = NA,
        ..correlations = NA,
        ..regression = NA,
        ..focused = NA,
        ..test = NA,
        ..msg1 = NA,
        ..msg2 = NA,
        ..msg3 = NA,
        ..residuals = NA)
)

jmvScaffoldResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvScaffoldResults",
    inherit = jmvcore::Group,
    active = list(
        storage = function() private$.items[["storage"]],
        info = function() private$.items[["info"]],
        main = function() private$.items[["main"]],
        mediansarray = function() private$.items[["mediansarray"]],
        regressionsarray = function() private$.items[["regressionsarray"]],
        randomarray = function() private$.items[["randomarray"]],
        residuals = function() private$.items[["residuals"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="jmvScaffold")
            self$add(jmvcore::Table$new(
                options=options,
                name="storage",
                visible=FALSE,
                clearWith=list(
                    "dep",
                    "regression"),
                columns=list(
                    list(
                        `name`="nothing"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Some Info",
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="specs", 
                        `type`="text", 
                        `title`="")),
                clearWith=list(
                    "dep")))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    means = function() private$.items[["means"]],
                    correlations = function() private$.items[["correlations"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="main",
                            title="Main Results")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="means",
                            title="Means",
                            clearWith=list(
                                "dep"),
                            columns=list(
                                list(
                                    `name`="source", 
                                    `title`="Source", 
                                    `type`="text"),
                                list(
                                    `name`="mean", 
                                    `title`="Mean<sub>ciao</sub>", 
                                    `type`="number"),
                                list(
                                    `name`="sd", 
                                    `type`="number", 
                                    `title`="SD"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="correlations",
                            title="correlations",
                            visible="(correlations)",
                            clearWith=list(
                                "dep",
                                "somevars"),
                            columns=list(
                                list(
                                    `name`="source", 
                                    `title`="Source", 
                                    `type`="text"))))}))$new(options=options))
            self$add(jmvcore::Array$new(
                options=options,
                name="mediansarray",
                title="Array with keys",
                visible="(focused)",
                items="(focused)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Some title:  ___key___",
                    clearWith=list(
                        "dep"),
                    columns=list(
                        list(
                            `name`="source", 
                            `title`="Source", 
                            `type`="text"),
                        list(
                            `name`="median", 
                            `title`="Median", 
                            `type`="number")))))
            self$add(jmvcore::Array$new(
                options=options,
                name="regressionsarray",
                title="Array with keys and two children tables",
                visible=FALSE,
                items="(focused)",
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        anova = function() private$.items[["anova"]],
                        regression = function() private$.items[["regression"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="Individual Analyses (Predictor ___key___ )")
                            self$add(jmvcore::Table$new(
                                options=options,
                                title="Anova title:  ___key___",
                                name="anova",
                                clearWith=list(
                                    "dep"),
                                columns=list(
                                    list(
                                        `name`="source", 
                                        `title`="Source", 
                                        `type`="text"),
                                    list(
                                        `name`="ss", 
                                        `title`="SS<sub>ciao</sub>", 
                                        `type`="number"),
                                    list(
                                        `name`="df", 
                                        `title`="df", 
                                        `type`="number"),
                                    list(
                                        `name`="f", 
                                        `title`="F", 
                                        `type`="number"),
                                    list(
                                        `name`="p", 
                                        `title`="p.", 
                                        `type`="number", 
                                        `format`="zto,pvalue"))))
                            self$add(jmvcore::Table$new(
                                options=options,
                                title="Regression title:  ___key___",
                                name="regression",
                                clearWith=list(
                                    "dep"),
                                columns=list(
                                    list(
                                        `name`="source", 
                                        `title`="Source", 
                                        `type`="text"),
                                    list(
                                        `name`="estimate", 
                                        `title`="Estimate", 
                                        `type`="number"),
                                    list(
                                        `name`="se", 
                                        `title`="SE", 
                                        `type`="number"),
                                    list(
                                        `name`="t", 
                                        `title`="t", 
                                        `type`="number"),
                                    list(
                                        `name`="p", 
                                        `title`="p", 
                                        `type`="number", 
                                        `format`="zto,pvalue"))))}))$new(options=options)))
            self$add(jmvcore::Array$new(
                options=options,
                name="randomarray",
                title="Array without keys",
                template=jmvcore::Table$new(
                    options=options,
                    title="Some title:  ___key___",
                    clearWith=list(
                        "dep"),
                    columns=list(
                        list(
                            `name`="source", 
                            `title`="Source<sub>ciao</sub>", 
                            `type`="text"),
                        list(
                            `name`="value", 
                            `title`="A number", 
                            `type`="number")))))
            self$add(jmvcore::Output$new(
                options=options,
                name="residuals",
                title="Residuals Vales",
                varTitle="`TEST_${ dep }`",
                varDescription="test values",
                clearWith=list(
                    "dep")))}))

jmvScaffoldBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvScaffoldBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvScaffold",
                name = "jmvScaffold",
                version = c(0,0,1),
                options = options,
                results = jmvScaffoldResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' jmvScaffold
#'
#' Something here
#' 
#'
#' @examples
#' \dontrun{
#' some code here
#'}
#' @param data the data as a data frame
#' @param dep a string naming the dependent variable from \code{data},
#'   variable must be numeric
#' @param somevars a string naming the dependent variable from \code{data},
#'   variable must be numeric
#' @param correlations \code{TRUE} or \code{FALSE} (default), shows
#'   correlation table
#' @param regression \code{TRUE} or \code{FALSE} (default), shows correlation
#'   table
#' @param focused .
#' @param test .
#' @param msg1 .
#' @param msg2 .
#' @param msg3 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$storage} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$main$means} \tab \tab \tab \tab \tab a table of R \cr
#'   \code{results$main$correlations} \tab \tab \tab \tab \tab a table of R \cr
#'   \code{results$mediansarray} \tab \tab \tab \tab \tab an array of keyed tables \cr
#'   \code{results$regressionsarray} \tab \tab \tab \tab \tab an array of keyed tables \cr
#'   \code{results$randomarray} \tab \tab \tab \tab \tab an array of N tables \cr
#'   \code{results$residuals} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$storage$asDF}
#'
#' \code{as.data.frame(results$storage)}
#'
#' @export
jmvScaffold <- function(
    data,
    dep = NULL,
    somevars = NULL,
    correlations = FALSE,
    regression = FALSE,
    focused = NULL,
    test = FALSE,
    msg1 = FALSE,
    msg2 = FALSE,
    msg3 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jmvScaffold requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(somevars)) somevars <- jmvcore::resolveQuo(jmvcore::enquo(somevars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(somevars), somevars, NULL))

    if (inherits(focused, "formula")) focused <- jmvcore::decomposeFormula(focused)

    options <- jmvScaffoldOptions$new(
        dep = dep,
        somevars = somevars,
        correlations = correlations,
        regression = regression,
        focused = focused,
        test = test,
        msg1 = msg1,
        msg2 = msg2,
        msg3 = msg3)

    analysis <- jmvScaffoldClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

